### PR TITLE
Feat/per request parameters

### PR DESCRIPTION
**Pull request by ercolanelli-leo**

### CODE REVIEW

**Comment by talaus-signifai** [comment]
This change made algoliasearchasync break for me

```
Traceback (most recent call last):
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "<string>", line 6, in _wrap_awaitable
  File "/Users/X/Projects/Y/y/file1.py", line 34, in func1
    self.autocomplete_attributes if self.autocomplete else None)
  File "/Users/X/Projects/Y/y/fil2.py", line 118, in func2
    algolia_result = await asyncio.ensure_future(index.search_async(query, query_args))
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/X/.pyenv/versions/3.6.3/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/algoliasearchasync/helpers.py", line 8, in async_
    return m(*args, **kwargs)
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/algoliasearch/index.py", line 472, in search
    return self._req(True, '/query', 'POST', request_options, data=params)
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/algoliasearch/index.py", line 1136, in _req
    return self.client._req(is_search, path, meth, request_options, params, data)
  File "/Users/X/.pyenv/versions/Y/lib/python3.6/site-packages/algoliasearch/client.py", line 685, in _req
    return self._transport.req(is_search, path, meth, params, data, request_options)
TypeError: req() takes from 4 to 6 positional arguments but 7 were given
```

Needless to say algoliasearch package is installed automatically by algoliasearchasync and is not locked to a specific version

Manually uninstalling algoliasearch 1.14.0 and installing 1.13.0 resolves this issue

**Comment by PLNech** [comment]
Hi @talaus-signifai, thanks for reporting this! I'm addressing this now and will release a fix at the soonest.

**Comment by PLNech** [comment]
@talaus-signifai: we just released [1.3.1](https://github.com/algolia/algoliasearch-client-python-async/releases/tag/1.3.1) which fixes this issue. Thanks again for your report!

**Comment by talaus-signifai** [comment]
Thanks for the quick turnaround, I will update the library on my end and report in case of issues

**Pull request merged**
