### PR TITLE
Fix ImportError when import algoliasearch

### PR DESCRIPTION
**Pull request by mekza**
Python 3.4

```
algoliasearch==1.5.0
```

I get this:

```
Traceback (most recent call last):
  File "list_grab.py", line 3, in <module>
    from algoliasearch import algoliasearch
  File "/Users/martin/Dev/Bright/twittermw/lib/python3.4/site-packages/algoliasearch/algoliasearch.py", line 45, in <module>
    from version import VERSION
ImportError: cannot import name 'VERSION'
```

### CODE REVIEW

**Comment by redox** [comment]
Oh interesting; didn't know about that syntax. Is it compatible with python 2.6 & 2.7?

**Comment by mekza** [comment]
Yep it tested it against 2.7.

**Comment by mekza** [comment]
@redox https://www.python.org/dev/peps/pep-0328/

**Comment by mekza** [comment]
My fork wasn't up to date. I don't why :/

**Comment by redox** [comment]
Let's see how it goes then. Thank you @mekza

**Comment by redox** [comment]
Just published the 1.5.1 version including this fix, happy coding :)

**Pull request merged**
