### PR TITLE
Add missing Python versions to the Travis configuration

### PR DESCRIPTION
**Pull request by aseure**

### CODE REVIEW

**Comment by PLNech** [comment]
LGTM :+1;

**Comment by aseure** [comment]
Last commit LGTM 👍

**Comment by ercolanelli-leo** [comment]
Even though it's fixed when tests are run locally it still doesn't seem to pass with Travis...

**Comment by redox** [comment]
```
FAILED (failures=1)
ERROR: InvocationError: '/home/travis/build/algolia/algoliasearch-client-python/.tox/py33/bin/nose2'
___________________________________ summary ____________________________________
ERROR:   py33: commands failed
```

**Comment by ercolanelli-leo** [comment]
It's actually stranger than expected:
- The tests are actually passing when launched locally
- On travis keys aren't updated even after 60 seconds (the maximum wait time), causing the test to fail

**Comment by redox** [comment]
`AssertionError: Items in the first set but not the second:`

That's because the test is wrongly computed. Since a lot of Travis instances will run at the same time, you should not try to diff the whole list of keys -> otherwise you're gonna be impacted by the other tests.

For the indices it's kind of OK because we use unique names.

**Comment by ercolanelli-leo** [comment]
@redox It makes sens for the `test_add_user_key` but the `test_add_user_index_key` is failing too, and shouldn't as indexes are indeed different between two Travis instances

**Pull request merged**
