### PR TITLE
Better, simpler, stronger :)

### LINKED ISSUE #20: SNI support on Python 2.x
https://urllib3.readthedocs.org/en/latest/security.html#pyopenssl

### LINKED ISSUE #22: If a key is rate limited, it's impossible to update it to no rate limit
https://github.com/algolia/algoliasearch-client-python/blob/master/algoliasearch/index.py#L824-L829

### PR DESCRIPTION
**Pull request by dethi**
* fix #22 
* fix #20 
* 100% backward compatible

### CODE REVIEW

**Comment by dethi** [comment]
:boom: all tests passed + 100% coverage!

**Comment by redox** [comment]
:+1: @dethi 
Can you just double-check with @Nagriar we're not loosing any keep-alive, timeout, SSL or SNI support -> that's our 4 hobby horses :)

It doesn't seem to break the backward compatibility, am I right?

**Comment by redox** [comment]
> 100% coverage

Yeah, that's because it's not parsing your code :)

screen shot 2015-07-27 at 08 19 03

**Comment by dethi** [comment]
:o I will fix that.
Yep, 99.9% backward compatible :). The only things that I removed is the encoding of `Decimal` to JSON. I don't understand why you added it. It's really scientific oriented.
However, if it is critical or a request from a client I can added it again.

**Comment by redox** [comment]
> The only things that I removed is the encoding of Decimal to JSON.

From what I remember, if you iterate over a MongoDB instance, all floating point numbers are `Decimal` and the default JSON encoder is not able to handle them.

**Comment by dethi** [comment]
Yep the default encoder can encode them. So I will add it again :)

**Comment by dethi** [comment]
@Nagriar can you review it, please? :smiley:

**Comment by dethi** [comment]
@redox Coveralls still have some problems. There is a lot of tweet about the same issue.

**Comment by Nagriar** [comment]
@dethi BOOM BOOM awesome! :+1:

**Pull request merged**
