### PR TITLE
Fix browse_from and browse_all

### PR DESCRIPTION
**Pull request by dethi**
refs #18 
@Jerskouille what do you think?

### CODE REVIEW

**Comment by redox** [comment]
We just need to understand how the tests could have passed before :) https://github.com/algolia/algoliasearch-client-python/blob/master/tests/test_client.py#L185-L210

**Comment by Jerskouille** [comment]
@dethi Thanks! This is great. Do you think we can bump the minor version and publish it (I don't know about pip and how to publish a python package) ?

**Comment by dethi** [comment]
Already done :+1:

**Comment by Jerskouille** [comment]
Nice! Thanks! :+1:

**Pull request merged**
